name: deploy

on:
  workflow_dispatch:

env:
  # the flutter application root
  PROJ_NAME: "Blink"
  # where the build number starts at
  BUILD_OFFSET: "100"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: write BUILD_WITH_OFFSET env
        run: echo -n "BUILD_WITH_OFFSET=$((${{ github.run_number }}+${{ env.BUILD_OFFSET }}))" >> $GITHUB_ENV

      - name: prepare arduino cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

      - name: install mbed nano
        run: ./bin/arduino-cli core install arduino:mbed_nano

      - name: compile
        run: ./bin/arduino-cli compile ${{ env.PROJ_NAME }}/${{ env.PROJ_NAME }}.ino --fqbn arduino:mbed_nano:nano33ble --output-dir out

      - name: zip
        run: zip -r out.zip out

      - name: generate CHANGELOG.md
        run: |
          git log -1 --pretty=format:"%b" > CHANGELOG.md

      - uses: ncipollo/release-action@v1
        with:
          name: "${{ env.GITVERSION_SEMVER }}+${{ env.BUILD_WITH_OFFSET }}"
          tag: "${{ env.GITVERSION_SEMVER }}"
          artifacts: "out.zip"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
